sign_common:
	gcc -g -o test_sign_common test_sign_common.c ../sign_common.{c,h} ../keygen.h ../numbers.{c,h} -lm
numbers:
	gcc -g -o test_numbers test_numbers.c ../numbers.{c,h} ../hash/libhash.a -lm  
